[2025-05-02 11:16:21 +0530] [772189] [INFO] Starting gunicorn 23.0.0
[2025-05-02 11:16:21 +0530] [772189] [INFO] Listening at: http://0.0.0.0:4332 (772189)
[2025-05-02 11:16:21 +0530] [772189] [INFO] Using worker: sync
[2025-05-02 11:16:21 +0530] [772190] [INFO] Booting worker with pid: 772190
[2025-05-02 11:17:12 +0530] [772468] [INFO] Starting gunicorn 23.0.0
[2025-05-02 11:17:12 +0530] [772468] [ERROR] Connection in use: ('0.0.0.0', 4332)
[2025-05-02 11:17:12 +0530] [772468] [ERROR] connection to ('0.0.0.0', 4332) failed: [Errno 98] Address already in use
[2025-05-02 11:17:13 +0530] [772468] [ERROR] Connection in use: ('0.0.0.0', 4332)
[2025-05-02 11:17:13 +0530] [772468] [ERROR] connection to ('0.0.0.0', 4332) failed: [Errno 98] Address already in use
[2025-05-02 11:17:14 +0530] [772468] [ERROR] Connection in use: ('0.0.0.0', 4332)
[2025-05-02 11:17:14 +0530] [772468] [ERROR] connection to ('0.0.0.0', 4332) failed: [Errno 98] Address already in use
[2025-05-02 11:17:15 +0530] [772468] [ERROR] Connection in use: ('0.0.0.0', 4332)
[2025-05-02 11:17:15 +0530] [772468] [ERROR] connection to ('0.0.0.0', 4332) failed: [Errno 98] Address already in use
[2025-05-02 11:17:16 +0530] [772468] [ERROR] Connection in use: ('0.0.0.0', 4332)
[2025-05-02 11:17:16 +0530] [772468] [ERROR] connection to ('0.0.0.0', 4332) failed: [Errno 98] Address already in use
[2025-05-02 11:17:17 +0530] [772468] [ERROR] Can't connect to ('0.0.0.0', 4332)
Not Found: /favicon.ico
Not Found: /favicon.ico
[2025-05-02 12:00:44 +0530] [772189] [CRITICAL] WORKER TIMEOUT (pid:772190)
[2025-05-02 06:30:44 +0000] [772190] [ERROR] Error handling request (no URI read)
Traceback (most recent call last):
  File "/home/everboltserver/invoice_project/env/lib/python3.12/site-packages/gunicorn/workers/sync.py", line 133, in handle
    req = next(parser)
          ^^^^^^^^^^^^
  File "/home/everboltserver/invoice_project/env/lib/python3.12/site-packages/gunicorn/http/parser.py", line 41, in __next__
    self.mesg = self.mesg_class(self.cfg, self.unreader, self.source_addr, self.req_count)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/everboltserver/invoice_project/env/lib/python3.12/site-packages/gunicorn/http/message.py", line 259, in __init__
    super().__init__(cfg, unreader, peer_addr)
  File "/home/everboltserver/invoice_project/env/lib/python3.12/site-packages/gunicorn/http/message.py", line 60, in __init__
    unused = self.parse(self.unreader)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/everboltserver/invoice_project/env/lib/python3.12/site-packages/gunicorn/http/message.py", line 271, in parse
    self.get_data(unreader, buf, stop=True)
  File "/home/everboltserver/invoice_project/env/lib/python3.12/site-packages/gunicorn/http/message.py", line 262, in get_data
    data = unreader.read()
           ^^^^^^^^^^^^^^^
  File "/home/everboltserver/invoice_project/env/lib/python3.12/site-packages/gunicorn/http/unreader.py", line 36, in read
    d = self.chunk()
        ^^^^^^^^^^^^
  File "/home/everboltserver/invoice_project/env/lib/python3.12/site-packages/gunicorn/http/unreader.py", line 63, in chunk
    return self.sock.recv(self.mxchunk)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/everboltserver/invoice_project/env/lib/python3.12/site-packages/gunicorn/workers/base.py", line 204, in handle_abort
    sys.exit(1)
SystemExit: 1
[2025-05-02 06:30:44 +0000] [772190] [INFO] Worker exiting (pid: 772190)
[2025-05-02 12:00:44 +0530] [784176] [INFO] Booting worker with pid: 784176
Internal Server Error: /
Traceback (most recent call last):
  File "/home/everboltserver/invoice_project/env/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/everboltserver/invoice_project/env/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/everboltserver/invoice_project/invoice_manager/views.py", line 16, in upload_invoice
    return render(request, 'invoice_manager/upload.html', {'form': form, 'invoices': invoices})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/everboltserver/invoice_project/env/lib/python3.12/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/everboltserver/invoice_project/env/lib/python3.12/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/everboltserver/invoice_project/env/lib/python3.12/site-packages/django/template/loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/everboltserver/invoice_project/env/lib/python3.12/site-packages/django/template/backends/django.py", line 79, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/everboltserver/invoice_project/env/lib/python3.12/site-packages/django/template/engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/everboltserver/invoice_project/env/lib/python3.12/site-packages/django/template/engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/everboltserver/invoice_project/env/lib/python3.12/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/everboltserver/invoice_project/env/lib/python3.12/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "/home/everboltserver/invoice_project/env/lib/python3.12/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/everboltserver/invoice_project/env/lib/python3.12/site-packages/django/template/base.py", line 196, in compile_nodelist
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "/home/everboltserver/invoice_project/env/lib/python3.12/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/home/everboltserver/invoice_project/env/lib/python3.12/site-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/everboltserver/invoice_project/env/lib/python3.12/site-packages/django/template/defaulttags.py", line 862, in do_for
    nodelist_loop = parser.parse(
                    ^^^^^^^^^^^^^
  File "/home/everboltserver/invoice_project/env/lib/python3.12/site-packages/django/template/base.py", line 489, in parse
    raise self.error(token, e)
  File "/home/everboltserver/invoice_project/env/lib/python3.12/site-packages/django/template/base.py", line 487, in parse
    filter_expression = self.compile_filter(token.contents)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/everboltserver/invoice_project/env/lib/python3.12/site-packages/django/template/base.py", line 609, in compile_filter
    return FilterExpression(token, self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/everboltserver/invoice_project/env/lib/python3.12/site-packages/django/template/base.py", line 705, in __init__
    filter_func = parser.find_filter(filter_name)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/everboltserver/invoice_project/env/lib/python3.12/site-packages/django/template/base.py", line 615, in find_filter
    raise TemplateSyntaxError("Invalid filter: '%s'" % filter_name)
django.template.exceptions.TemplateSyntaxError: Invalid filter: 'basename'
Not Found: /favicon.ico
[2025-05-02 12:01:57 +0530] [772189] [CRITICAL] WORKER TIMEOUT (pid:784176)
[2025-05-02 06:31:57 +0000] [784176] [ERROR] Error handling request (no URI read)
Traceback (most recent call last):
  File "/home/everboltserver/invoice_project/env/lib/python3.12/site-packages/gunicorn/workers/sync.py", line 133, in handle
    req = next(parser)
          ^^^^^^^^^^^^
  File "/home/everboltserver/invoice_project/env/lib/python3.12/site-packages/gunicorn/http/parser.py", line 41, in __next__
    self.mesg = self.mesg_class(self.cfg, self.unreader, self.source_addr, self.req_count)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/everboltserver/invoice_project/env/lib/python3.12/site-packages/gunicorn/http/message.py", line 259, in __init__
    super().__init__(cfg, unreader, peer_addr)
  File "/home/everboltserver/invoice_project/env/lib/python3.12/site-packages/gunicorn/http/message.py", line 60, in __init__
    unused = self.parse(self.unreader)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/everboltserver/invoice_project/env/lib/python3.12/site-packages/gunicorn/http/message.py", line 271, in parse
    self.get_data(unreader, buf, stop=True)
  File "/home/everboltserver/invoice_project/env/lib/python3.12/site-packages/gunicorn/http/message.py", line 262, in get_data
    data = unreader.read()
           ^^^^^^^^^^^^^^^
  File "/home/everboltserver/invoice_project/env/lib/python3.12/site-packages/gunicorn/http/unreader.py", line 36, in read
    d = self.chunk()
        ^^^^^^^^^^^^
  File "/home/everboltserver/invoice_project/env/lib/python3.12/site-packages/gunicorn/http/unreader.py", line 63, in chunk
    return self.sock.recv(self.mxchunk)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/everboltserver/invoice_project/env/lib/python3.12/site-packages/gunicorn/workers/base.py", line 204, in handle_abort
    sys.exit(1)
SystemExit: 1
[2025-05-02 06:31:57 +0000] [784176] [INFO] Worker exiting (pid: 784176)
[2025-05-02 12:01:57 +0530] [784285] [INFO] Booting worker with pid: 784285
Internal Server Error: /
Traceback (most recent call last):
  File "/home/everboltserver/invoice_project/env/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/everboltserver/invoice_project/env/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/everboltserver/invoice_project/invoice_manager/views.py", line 16, in upload_invoice
    return render(request, 'invoice_manager/upload.html', {'form': form, 'invoices': invoices})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/everboltserver/invoice_project/env/lib/python3.12/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/everboltserver/invoice_project/env/lib/python3.12/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/everboltserver/invoice_project/env/lib/python3.12/site-packages/django/template/loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/everboltserver/invoice_project/env/lib/python3.12/site-packages/django/template/backends/django.py", line 79, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/everboltserver/invoice_project/env/lib/python3.12/site-packages/django/template/engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/everboltserver/invoice_project/env/lib/python3.12/site-packages/django/template/engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/everboltserver/invoice_project/env/lib/python3.12/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/everboltserver/invoice_project/env/lib/python3.12/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "/home/everboltserver/invoice_project/env/lib/python3.12/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/everboltserver/invoice_project/env/lib/python3.12/site-packages/django/template/base.py", line 196, in compile_nodelist
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "/home/everboltserver/invoice_project/env/lib/python3.12/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/home/everboltserver/invoice_project/env/lib/python3.12/site-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/everboltserver/invoice_project/env/lib/python3.12/site-packages/django/template/defaulttags.py", line 862, in do_for
    nodelist_loop = parser.parse(
                    ^^^^^^^^^^^^^
  File "/home/everboltserver/invoice_project/env/lib/python3.12/site-packages/django/template/base.py", line 489, in parse
    raise self.error(token, e)
  File "/home/everboltserver/invoice_project/env/lib/python3.12/site-packages/django/template/base.py", line 487, in parse
    filter_expression = self.compile_filter(token.contents)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/everboltserver/invoice_project/env/lib/python3.12/site-packages/django/template/base.py", line 609, in compile_filter
    return FilterExpression(token, self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/everboltserver/invoice_project/env/lib/python3.12/site-packages/django/template/base.py", line 705, in __init__
    filter_func = parser.find_filter(filter_name)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/everboltserver/invoice_project/env/lib/python3.12/site-packages/django/template/base.py", line 615, in find_filter
    raise TemplateSyntaxError("Invalid filter: '%s'" % filter_name)
django.template.exceptions.TemplateSyntaxError: Invalid filter: 'basename'
[2025-05-02 12:03:33 +0530] [772189] [CRITICAL] WORKER TIMEOUT (pid:784285)
[2025-05-02 06:33:33 +0000] [784285] [ERROR] Error handling request (no URI read)
Traceback (most recent call last):
  File "/home/everboltserver/invoice_project/env/lib/python3.12/site-packages/gunicorn/workers/sync.py", line 133, in handle
    req = next(parser)
          ^^^^^^^^^^^^
  File "/home/everboltserver/invoice_project/env/lib/python3.12/site-packages/gunicorn/http/parser.py", line 41, in __next__
    self.mesg = self.mesg_class(self.cfg, self.unreader, self.source_addr, self.req_count)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/everboltserver/invoice_project/env/lib/python3.12/site-packages/gunicorn/http/message.py", line 259, in __init__
    super().__init__(cfg, unreader, peer_addr)
  File "/home/everboltserver/invoice_project/env/lib/python3.12/site-packages/gunicorn/http/message.py", line 60, in __init__
    unused = self.parse(self.unreader)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/everboltserver/invoice_project/env/lib/python3.12/site-packages/gunicorn/http/message.py", line 271, in parse
    self.get_data(unreader, buf, stop=True)
  File "/home/everboltserver/invoice_project/env/lib/python3.12/site-packages/gunicorn/http/message.py", line 262, in get_data
    data = unreader.read()
           ^^^^^^^^^^^^^^^
  File "/home/everboltserver/invoice_project/env/lib/python3.12/site-packages/gunicorn/http/unreader.py", line 36, in read
    d = self.chunk()
        ^^^^^^^^^^^^
  File "/home/everboltserver/invoice_project/env/lib/python3.12/site-packages/gunicorn/http/unreader.py", line 63, in chunk
    return self.sock.recv(self.mxchunk)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/everboltserver/invoice_project/env/lib/python3.12/site-packages/gunicorn/workers/base.py", line 204, in handle_abort
    sys.exit(1)
SystemExit: 1
[2025-05-02 06:33:33 +0000] [784285] [INFO] Worker exiting (pid: 784285)
[2025-05-02 12:03:33 +0530] [784359] [INFO] Booting worker with pid: 784359
[2025-05-02 12:08:45 +0530] [772189] [CRITICAL] WORKER TIMEOUT (pid:784359)
[2025-05-02 06:38:45 +0000] [784359] [ERROR] Error handling request (no URI read)
Traceback (most recent call last):
  File "/home/everboltserver/invoice_project/env/lib/python3.12/site-packages/gunicorn/workers/sync.py", line 133, in handle
    req = next(parser)
          ^^^^^^^^^^^^
  File "/home/everboltserver/invoice_project/env/lib/python3.12/site-packages/gunicorn/http/parser.py", line 41, in __next__
    self.mesg = self.mesg_class(self.cfg, self.unreader, self.source_addr, self.req_count)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/everboltserver/invoice_project/env/lib/python3.12/site-packages/gunicorn/http/message.py", line 259, in __init__
    super().__init__(cfg, unreader, peer_addr)
  File "/home/everboltserver/invoice_project/env/lib/python3.12/site-packages/gunicorn/http/message.py", line 60, in __init__
    unused = self.parse(self.unreader)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/everboltserver/invoice_project/env/lib/python3.12/site-packages/gunicorn/http/message.py", line 271, in parse
    self.get_data(unreader, buf, stop=True)
  File "/home/everboltserver/invoice_project/env/lib/python3.12/site-packages/gunicorn/http/message.py", line 262, in get_data
    data = unreader.read()
           ^^^^^^^^^^^^^^^
  File "/home/everboltserver/invoice_project/env/lib/python3.12/site-packages/gunicorn/http/unreader.py", line 36, in read
    d = self.chunk()
        ^^^^^^^^^^^^
  File "/home/everboltserver/invoice_project/env/lib/python3.12/site-packages/gunicorn/http/unreader.py", line 63, in chunk
    return self.sock.recv(self.mxchunk)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/everboltserver/invoice_project/env/lib/python3.12/site-packages/gunicorn/workers/base.py", line 204, in handle_abort
    sys.exit(1)
SystemExit: 1
[2025-05-02 06:38:45 +0000] [784359] [INFO] Worker exiting (pid: 784359)
[2025-05-02 12:08:45 +0530] [784681] [INFO] Booting worker with pid: 784681
[2025-05-02 12:10:05 +0530] [772189] [CRITICAL] WORKER TIMEOUT (pid:784681)
[2025-05-02 06:40:05 +0000] [784681] [ERROR] Error handling request (no URI read)
Traceback (most recent call last):
  File "/home/everboltserver/invoice_project/env/lib/python3.12/site-packages/gunicorn/workers/sync.py", line 133, in handle
    req = next(parser)
          ^^^^^^^^^^^^
  File "/home/everboltserver/invoice_project/env/lib/python3.12/site-packages/gunicorn/http/parser.py", line 41, in __next__
    self.mesg = self.mesg_class(self.cfg, self.unreader, self.source_addr, self.req_count)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/everboltserver/invoice_project/env/lib/python3.12/site-packages/gunicorn/http/message.py", line 259, in __init__
    super().__init__(cfg, unreader, peer_addr)
  File "/home/everboltserver/invoice_project/env/lib/python3.12/site-packages/gunicorn/http/message.py", line 60, in __init__
    unused = self.parse(self.unreader)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/everboltserver/invoice_project/env/lib/python3.12/site-packages/gunicorn/http/message.py", line 271, in parse
    self.get_data(unreader, buf, stop=True)
  File "/home/everboltserver/invoice_project/env/lib/python3.12/site-packages/gunicorn/http/message.py", line 262, in get_data
    data = unreader.read()
           ^^^^^^^^^^^^^^^
  File "/home/everboltserver/invoice_project/env/lib/python3.12/site-packages/gunicorn/http/unreader.py", line 36, in read
    d = self.chunk()
        ^^^^^^^^^^^^
  File "/home/everboltserver/invoice_project/env/lib/python3.12/site-packages/gunicorn/http/unreader.py", line 63, in chunk
    return self.sock.recv(self.mxchunk)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/everboltserver/invoice_project/env/lib/python3.12/site-packages/gunicorn/workers/base.py", line 204, in handle_abort
    sys.exit(1)
SystemExit: 1
[2025-05-02 06:40:05 +0000] [784681] [INFO] Worker exiting (pid: 784681)
[2025-05-02 12:10:05 +0530] [784745] [INFO] Booting worker with pid: 784745
[2025-05-02 12:19:36 +0530] [772189] [CRITICAL] WORKER TIMEOUT (pid:784745)
[2025-05-02 06:49:36 +0000] [784745] [ERROR] Error handling request (no URI read)
Traceback (most recent call last):
  File "/home/everboltserver/invoice_project/env/lib/python3.12/site-packages/gunicorn/workers/sync.py", line 133, in handle
    req = next(parser)
          ^^^^^^^^^^^^
  File "/home/everboltserver/invoice_project/env/lib/python3.12/site-packages/gunicorn/http/parser.py", line 41, in __next__
    self.mesg = self.mesg_class(self.cfg, self.unreader, self.source_addr, self.req_count)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/everboltserver/invoice_project/env/lib/python3.12/site-packages/gunicorn/http/message.py", line 259, in __init__
    super().__init__(cfg, unreader, peer_addr)
  File "/home/everboltserver/invoice_project/env/lib/python3.12/site-packages/gunicorn/http/message.py", line 60, in __init__
    unused = self.parse(self.unreader)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/everboltserver/invoice_project/env/lib/python3.12/site-packages/gunicorn/http/message.py", line 271, in parse
    self.get_data(unreader, buf, stop=True)
  File "/home/everboltserver/invoice_project/env/lib/python3.12/site-packages/gunicorn/http/message.py", line 262, in get_data
    data = unreader.read()
           ^^^^^^^^^^^^^^^
  File "/home/everboltserver/invoice_project/env/lib/python3.12/site-packages/gunicorn/http/unreader.py", line 36, in read
    d = self.chunk()
        ^^^^^^^^^^^^
  File "/home/everboltserver/invoice_project/env/lib/python3.12/site-packages/gunicorn/http/unreader.py", line 63, in chunk
    return self.sock.recv(self.mxchunk)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/everboltserver/invoice_project/env/lib/python3.12/site-packages/gunicorn/workers/base.py", line 204, in handle_abort
    sys.exit(1)
SystemExit: 1
[2025-05-02 06:49:36 +0000] [784745] [INFO] Worker exiting (pid: 784745)
[2025-05-02 12:19:36 +0530] [785178] [INFO] Booting worker with pid: 785178
Not Found: /favicon.ico
[2025-05-02 12:21:25 +0530] [772189] [CRITICAL] WORKER TIMEOUT (pid:785178)
[2025-05-02 06:51:25 +0000] [785178] [ERROR] Error handling request (no URI read)
Traceback (most recent call last):
  File "/home/everboltserver/invoice_project/env/lib/python3.12/site-packages/gunicorn/workers/sync.py", line 133, in handle
    req = next(parser)
          ^^^^^^^^^^^^
  File "/home/everboltserver/invoice_project/env/lib/python3.12/site-packages/gunicorn/http/parser.py", line 41, in __next__
    self.mesg = self.mesg_class(self.cfg, self.unreader, self.source_addr, self.req_count)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/everboltserver/invoice_project/env/lib/python3.12/site-packages/gunicorn/http/message.py", line 259, in __init__
    super().__init__(cfg, unreader, peer_addr)
  File "/home/everboltserver/invoice_project/env/lib/python3.12/site-packages/gunicorn/http/message.py", line 60, in __init__
    unused = self.parse(self.unreader)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/everboltserver/invoice_project/env/lib/python3.12/site-packages/gunicorn/http/message.py", line 271, in parse
    self.get_data(unreader, buf, stop=True)
  File "/home/everboltserver/invoice_project/env/lib/python3.12/site-packages/gunicorn/http/message.py", line 262, in get_data
    data = unreader.read()
           ^^^^^^^^^^^^^^^
  File "/home/everboltserver/invoice_project/env/lib/python3.12/site-packages/gunicorn/http/unreader.py", line 36, in read
    d = self.chunk()
        ^^^^^^^^^^^^
  File "/home/everboltserver/invoice_project/env/lib/python3.12/site-packages/gunicorn/http/unreader.py", line 63, in chunk
    return self.sock.recv(self.mxchunk)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/everboltserver/invoice_project/env/lib/python3.12/site-packages/gunicorn/workers/base.py", line 204, in handle_abort
    sys.exit(1)
SystemExit: 1
[2025-05-02 06:51:25 +0000] [785178] [INFO] Worker exiting (pid: 785178)
[2025-05-02 12:21:25 +0530] [785266] [INFO] Booting worker with pid: 785266
[2025-05-02 12:23:04 +0530] [772189] [CRITICAL] WORKER TIMEOUT (pid:785266)
[2025-05-02 06:53:04 +0000] [785266] [ERROR] Error handling request (no URI read)
Traceback (most recent call last):
  File "/home/everboltserver/invoice_project/env/lib/python3.12/site-packages/gunicorn/workers/sync.py", line 133, in handle
    req = next(parser)
          ^^^^^^^^^^^^
  File "/home/everboltserver/invoice_project/env/lib/python3.12/site-packages/gunicorn/http/parser.py", line 41, in __next__
    self.mesg = self.mesg_class(self.cfg, self.unreader, self.source_addr, self.req_count)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/everboltserver/invoice_project/env/lib/python3.12/site-packages/gunicorn/http/message.py", line 259, in __init__
    super().__init__(cfg, unreader, peer_addr)
  File "/home/everboltserver/invoice_project/env/lib/python3.12/site-packages/gunicorn/http/message.py", line 60, in __init__
    unused = self.parse(self.unreader)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/everboltserver/invoice_project/env/lib/python3.12/site-packages/gunicorn/http/message.py", line 271, in parse
    self.get_data(unreader, buf, stop=True)
  File "/home/everboltserver/invoice_project/env/lib/python3.12/site-packages/gunicorn/http/message.py", line 262, in get_data
    data = unreader.read()
           ^^^^^^^^^^^^^^^
  File "/home/everboltserver/invoice_project/env/lib/python3.12/site-packages/gunicorn/http/unreader.py", line 36, in read
    d = self.chunk()
        ^^^^^^^^^^^^
  File "/home/everboltserver/invoice_project/env/lib/python3.12/site-packages/gunicorn/http/unreader.py", line 63, in chunk
    return self.sock.recv(self.mxchunk)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/everboltserver/invoice_project/env/lib/python3.12/site-packages/gunicorn/workers/base.py", line 204, in handle_abort
    sys.exit(1)
SystemExit: 1
[2025-05-02 06:53:04 +0000] [785266] [INFO] Worker exiting (pid: 785266)
[2025-05-02 12:23:04 +0530] [785342] [INFO] Booting worker with pid: 785342
[2025-05-02 12:26:53 +0530] [772189] [CRITICAL] WORKER TIMEOUT (pid:785342)
[2025-05-02 06:56:53 +0000] [785342] [ERROR] Error handling request (no URI read)
Traceback (most recent call last):
  File "/home/everboltserver/invoice_project/env/lib/python3.12/site-packages/gunicorn/workers/sync.py", line 133, in handle
    req = next(parser)
          ^^^^^^^^^^^^
  File "/home/everboltserver/invoice_project/env/lib/python3.12/site-packages/gunicorn/http/parser.py", line 41, in __next__
    self.mesg = self.mesg_class(self.cfg, self.unreader, self.source_addr, self.req_count)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/everboltserver/invoice_project/env/lib/python3.12/site-packages/gunicorn/http/message.py", line 259, in __init__
    super().__init__(cfg, unreader, peer_addr)
  File "/home/everboltserver/invoice_project/env/lib/python3.12/site-packages/gunicorn/http/message.py", line 60, in __init__
    unused = self.parse(self.unreader)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/everboltserver/invoice_project/env/lib/python3.12/site-packages/gunicorn/http/message.py", line 271, in parse
    self.get_data(unreader, buf, stop=True)
  File "/home/everboltserver/invoice_project/env/lib/python3.12/site-packages/gunicorn/http/message.py", line 262, in get_data
    data = unreader.read()
           ^^^^^^^^^^^^^^^
  File "/home/everboltserver/invoice_project/env/lib/python3.12/site-packages/gunicorn/http/unreader.py", line 36, in read
    d = self.chunk()
        ^^^^^^^^^^^^
  File "/home/everboltserver/invoice_project/env/lib/python3.12/site-packages/gunicorn/http/unreader.py", line 63, in chunk
    return self.sock.recv(self.mxchunk)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/everboltserver/invoice_project/env/lib/python3.12/site-packages/gunicorn/workers/base.py", line 204, in handle_abort
    sys.exit(1)
SystemExit: 1
[2025-05-02 06:56:53 +0000] [785342] [INFO] Worker exiting (pid: 785342)
[2025-05-02 12:26:53 +0530] [785556] [INFO] Booting worker with pid: 785556
Not Found: /favicon.ico
Not Found: /robots.txt
Not Found: /favicon.ico
Not Found: /favicon.ico
Not Found: /favicon.ico
Not Found: /favicon.ico
Not Found: /favicon.ico
Not Found: /favicon.ico
Not Found: /favicon.ico
Not Found: /favicon.ico
[2025-05-02 12:44:02 +0530] [772189] [CRITICAL] WORKER TIMEOUT (pid:785556)
[2025-05-02 07:14:02 +0000] [785556] [ERROR] Error handling request (no URI read)
Traceback (most recent call last):
  File "/home/everboltserver/invoice_project/env/lib/python3.12/site-packages/gunicorn/workers/sync.py", line 133, in handle
    req = next(parser)
          ^^^^^^^^^^^^
  File "/home/everboltserver/invoice_project/env/lib/python3.12/site-packages/gunicorn/http/parser.py", line 41, in __next__
    self.mesg = self.mesg_class(self.cfg, self.unreader, self.source_addr, self.req_count)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/everboltserver/invoice_project/env/lib/python3.12/site-packages/gunicorn/http/message.py", line 259, in __init__
    super().__init__(cfg, unreader, peer_addr)
  File "/home/everboltserver/invoice_project/env/lib/python3.12/site-packages/gunicorn/http/message.py", line 60, in __init__
    unused = self.parse(self.unreader)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/everboltserver/invoice_project/env/lib/python3.12/site-packages/gunicorn/http/message.py", line 271, in parse
    self.get_data(unreader, buf, stop=True)
  File "/home/everboltserver/invoice_project/env/lib/python3.12/site-packages/gunicorn/http/message.py", line 262, in get_data
    data = unreader.read()
           ^^^^^^^^^^^^^^^
  File "/home/everboltserver/invoice_project/env/lib/python3.12/site-packages/gunicorn/http/unreader.py", line 36, in read
    d = self.chunk()
        ^^^^^^^^^^^^
  File "/home/everboltserver/invoice_project/env/lib/python3.12/site-packages/gunicorn/http/unreader.py", line 63, in chunk
    return self.sock.recv(self.mxchunk)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/everboltserver/invoice_project/env/lib/python3.12/site-packages/gunicorn/workers/base.py", line 204, in handle_abort
    sys.exit(1)
SystemExit: 1
[2025-05-02 07:14:02 +0000] [785556] [INFO] Worker exiting (pid: 785556)
[2025-05-02 12:44:02 +0530] [786535] [INFO] Booting worker with pid: 786535
Not Found: /static/css/bootstrap.min.css
Not Found: /favicon.ico
Not Found: /static/css/bootstrap.min.css
Not Found: /static/css/bootstrap.min.css
Not Found: /static/css/bootstrap.min.css
Not Found: /static/css/bootstrap.min.css
Not Found: /static/css/bootstrap.min.css
Not Found: /static/css/bootstrap.min.css
Not Found: /static/css/bootstrap.min.css
Not Found: /static/css/bootstrap.min.css
Not Found: /static/css/bootstrap.min.css
Not Found: /static/css/bootstrap.min.css
Not Found: /static/css/bootstrap.min.css
Not Found: /static/css/bootstrap.min.css
Not Found: /static/css/bootstrap.min.css
Not Found: /static/css/bootstrap.min.css
Not Found: /static/css/bootstrap.min.css
Not Found: /static/css/bootstrap.min.css
Not Found: /static/css/bootstrap.min.css
[2025-05-02 12:59:51 +0530] [772189] [INFO] Handling signal: term
[2025-05-02 13:00:22 +0530] [772189] [INFO] Shutting down: Master
